#!/usr/bin/env python3

"""Generate the Gini Granularity curve and calculates the area under the curve
Takes a .tsv format file generated by GG_out_merge.py, structured as:

W    D1   D2   D3  ...
1     G    G    G  ...
2     G    G    G  ...
3     G    G    G  ...
...

Where Dn refers to a dataset, W refers to window size, and G is the Gini.

Dependancies:
Python3.6<=
argparse
numpy
matplotlib
seaborn
"""

import argparse
import sys
import os
import numpy as  np
import matplotlib.pyplot as plt
