#!/usr/bin/env python3

"""Generate a .tsv format file from an arbitrary number of files generated by gini.py, structured as:

W    D1   D2   D3  ...
1     G    G    G  ...
2     G    G    G  ...
3     G    G    G  ...
...

Where Dn refers to a dataset, W refers to window size, and G is the Gini.

Dependancies:
Python3.6<=
argparse
"""

import argparse
import sys
import os

def main(argv):

    parser = argparse.ArgumentParser()

    parser.add_argument('script_path', action='store', help=argparse.SUPPRESS)
    parser.add_argument('Gini-files',  action='store', help='Files generated by gini.py to merge.')

    args = parser.parse_args(argv)



if __name__ == "__main__":
    if len(sys.argv) < 2 or "-h" in sys.argv:
        print(__doc__)
        main([sys.argv[0], "-h"])
        sys.exit(1)
    main(sys.argv)
